version: "2"

services:
  app:
    environment:
      DJANGO_MANAGEPY_MIGRATE: "on"
      DATABASE_URL: "sqlite:////code/data/sqlite3.db"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./mnt/data:/code/data
